<?php

class LibXMLError_parser
{
    private $domains = array(
        0 => array('libxml_constant' =>  'XML_FROM_NONE', 'name' => ''),
        1 => array('libxml_constant' =>  'XML_FROM_PARSER', 'name' => 'XML parser'),
        2 => array('libxml_constant' =>  'XML_FROM_TREE', 'name' => 'Tree module'),
        3 => array('libxml_constant' =>  'XML_FROM_NAMESPACE  ', 'name' => 'XML Namespace module'),
        4 => array('libxml_constant' =>  'XML_FROM_DTD', 'name' => 'XML DTD validation with parser context'),
        5 => array('libxml_constant' =>  'XML_FROM_HTML', 'name' => 'HTML parser'),
        6 => array('libxml_constant' =>  'XML_FROM_MEMORY', 'name' => 'Memory allocator'),
        7 => array('libxml_constant' =>  'XML_FROM_OUTPUT', 'name' => 'Serialization code'),
        8 => array('libxml_constant' =>  'XML_FROM_IO', 'name' => 'Input/Output stack'),
        9 => array('libxml_constant' =>  'XML_FROM_FTP', 'name' => 'FTP module'),
        10 => array('libxml_constant' => 'XML_FROM_HTTP', 'name' => 'HTTP module'),
        11 => array('libxml_constant' => 'XML_FROM_XINCLUDE', 'name' => 'XInclude processing'),
        12 => array('libxml_constant' => 'XML_FROM_XPATH', 'name' => 'XPath module'),
        13 => array('libxml_constant' => 'XML_FROM_XPOINTER', 'name' => 'XPointer module'),
        14 => array('libxml_constant' => 'XML_FROM_REGEXP', 'name' => 'Regular expressions module'),
        15 => array('libxml_constant' => 'XML_FROM_DATATYPE', 'name' => 'W3C XML Schemas Datatype module'),
        16 => array('libxml_constant' => 'XML_FROM_SCHEMASP', 'name' => 'W3C XML Schemas parser module'),
        17 => array('libxml_constant' => 'XML_FROM_SCHEMASV', 'name' => 'W3C XML Schemas validation module'),
        18 => array('libxml_constant' => 'XML_FROM_RELAXNGP', 'name' => 'Relax-NG parser module'),
        19 => array('libxml_constant' => 'XML_FROM_RELAXNGV', 'name' => 'Relax-NG validator module'),
        20 => array('libxml_constant' => 'XML_FROM_CATALOG', 'name' => 'Catalog module'),
        21 => array('libxml_constant' => 'XML_FROM_C14N', 'name' => 'Canonicalization module'),
        22 => array('libxml_constant' => 'XML_FROM_XSLT', 'name' => 'XSLT engine from libxslt'),
        23 => array('libxml_constant' => 'XML_FROM_VALID', 'name' => 'XML DTD validation with valid context'),
        24 => array('libxml_constant' => 'XML_FROM_CHECK', 'name' => 'Error checking module'),
        25 => array('libxml_constant' => 'XML_FROM_WRITER', 'name' => 'xmlwriter module'),
        26 => array('libxml_constant' => 'XML_FROM_MODULE', 'name' => 'dynamically loaded module module'),
        27 => array('libxml_constant' => 'XML_FROM_I18N', 'name' => 'module handling character conversion'),
        28 => array('libxml_constant' => 'XML_FROM_SCHEMATRONV', 'name' => 'Schematron validator module'),
        29 => array('libxml_constant' => 'XML_FROM_BUFFER', 'name' => 'Buffers module'),
        30 => array('libxml_constant' => 'XML_FROM_URI', 'name' => 'URI module'),
    );
    
    private $errors = array(
        0 => array('libxml_constant' => 'XML_ERR_OK', 'description' => ''),
        1 => array('libxml_constant' => 'XML_ERR_INTERNAL_ERROR', 'description' => ''),
        2 => array('libxml_constant' => 'XML_ERR_NO_MEMORY', 'description' => ''),
        3 => array('libxml_constant' => 'XML_ERR_DOCUMENT_START', 'description' => ''),
        4 => array('libxml_constant' => 'XML_ERR_DOCUMENT_EMPTY', 'description' => ''),
        5 => array('libxml_constant' => 'XML_ERR_DOCUMENT_END', 'description' => ''),
        6 => array('libxml_constant' => 'XML_ERR_INVALID_HEX_CHARREF', 'description' => ''),
        7 => array('libxml_constant' => 'XML_ERR_INVALID_DEC_CHARREF', 'description' => ''),
        8 => array('libxml_constant' => 'XML_ERR_INVALID_CHARREF', 'description' => ''),
        9 => array('libxml_constant' => 'XML_ERR_INVALID_CHAR', 'description' => ''),
        10 => array('libxml_constant' => 'XML_ERR_CHARREF_AT_EOF', 'description' => ''),
        11 => array('libxml_constant' => 'XML_ERR_CHARREF_IN_PROLOG', 'description' => ''),
        12 => array('libxml_constant' => 'XML_ERR_CHARREF_IN_EPILOG', 'description' => ''),
        13 => array('libxml_constant' => 'XML_ERR_CHARREF_IN_DTD', 'description' => ''),
        14 => array('libxml_constant' => 'XML_ERR_ENTITYREF_AT_EOF', 'description' => ''),
        15 => array('libxml_constant' => 'XML_ERR_ENTITYREF_IN_PROLOG', 'description' => ''),
        16 => array('libxml_constant' => 'XML_ERR_ENTITYREF_IN_EPILOG', 'description' => ''),
        17 => array('libxml_constant' => 'XML_ERR_ENTITYREF_IN_DTD', 'description' => ''),
        18 => array('libxml_constant' => 'XML_ERR_PEREF_AT_EOF', 'description' => ''),
        19 => array('libxml_constant' => 'XML_ERR_PEREF_IN_PROLOG', 'description' => ''),
        20 => array('libxml_constant' => 'XML_ERR_PEREF_IN_EPILOG', 'description' => ''),
        21 => array('libxml_constant' => 'XML_ERR_PEREF_IN_INT_SUBSET', 'description' => ''),
        22 => array('libxml_constant' => 'XML_ERR_ENTITYREF_NO_NAME', 'description' => ''),
        23 => array('libxml_constant' => 'XML_ERR_ENTITYREF_SEMICOL_MISSING', 'description' => ''),
        24 => array('libxml_constant' => 'XML_ERR_PEREF_NO_NAME', 'description' => ''),
        25 => array('libxml_constant' => 'XML_ERR_PEREF_SEMICOL_MISSING', 'description' => ''),
        26 => array('libxml_constant' => 'XML_ERR_UNDECLARED_ENTITY', 'description' => ''),
        27 => array('libxml_constant' => 'XML_WAR_UNDECLARED_ENTITY', 'description' => ''),
        28 => array('libxml_constant' => 'XML_ERR_UNPARSED_ENTITY', 'description' => ''),
        29 => array('libxml_constant' => 'XML_ERR_ENTITY_IS_EXTERNAL', 'description' => ''),
        30 => array('libxml_constant' => 'XML_ERR_ENTITY_IS_PARAMETER', 'description' => ''),
        31 => array('libxml_constant' => 'XML_ERR_UNKNOWN_ENCODING', 'description' => ''),
        32 => array('libxml_constant' => 'XML_ERR_UNSUPPORTED_ENCODING', 'description' => ''),
        33 => array('libxml_constant' => 'XML_ERR_STRING_NOT_STARTED', 'description' => ''),
        34 => array('libxml_constant' => 'XML_ERR_STRING_NOT_CLOSED', 'description' => ''),
        35 => array('libxml_constant' => 'XML_ERR_NS_DECL_ERROR', 'description' => ''),
        36 => array('libxml_constant' => 'XML_ERR_ENTITY_NOT_STARTED', 'description' => ''),
        37 => array('libxml_constant' => 'XML_ERR_ENTITY_NOT_FINISHED', 'description' => ''),
        38 => array('libxml_constant' => 'XML_ERR_LT_IN_ATTRIBUTE', 'description' => ''),
        39 => array('libxml_constant' => 'XML_ERR_ATTRIBUTE_NOT_STARTED', 'description' => ''),
        40 => array('libxml_constant' => 'XML_ERR_ATTRIBUTE_NOT_FINISHED', 'description' => ''),
        41 => array('libxml_constant' => 'XML_ERR_ATTRIBUTE_WITHOUT_VALUE', 'description' => ''),
        42 => array('libxml_constant' => 'XML_ERR_ATTRIBUTE_REDEFINED', 'description' => ''),
        43 => array('libxml_constant' => 'XML_ERR_LITERAL_NOT_STARTED', 'description' => ''),
        44 => array('libxml_constant' => 'XML_ERR_LITERAL_NOT_FINISHED', 'description' => ''),
        45 => array('libxml_constant' => 'XML_ERR_COMMENT_NOT_FINISHED', 'description' => ''),
        46 => array('libxml_constant' => 'XML_ERR_PI_NOT_STARTED', 'description' => ''),
        47 => array('libxml_constant' => 'XML_ERR_PI_NOT_FINISHED', 'description' => ''),
        48 => array('libxml_constant' => 'XML_ERR_NOTATION_NOT_STARTED', 'description' => ''),
        49 => array('libxml_constant' => 'XML_ERR_NOTATION_NOT_FINISHED', 'description' => ''),
        50 => array('libxml_constant' => 'XML_ERR_ATTLIST_NOT_STARTED', 'description' => ''),
        51 => array('libxml_constant' => 'XML_ERR_ATTLIST_NOT_FINISHED', 'description' => ''),
        52 => array('libxml_constant' => 'XML_ERR_MIXED_NOT_STARTED', 'description' => ''),
        53 => array('libxml_constant' => 'XML_ERR_MIXED_NOT_FINISHED', 'description' => ''),
        54 => array('libxml_constant' => 'XML_ERR_ELEMCONTENT_NOT_STARTED', 'description' => ''),
        55 => array('libxml_constant' => 'XML_ERR_ELEMCONTENT_NOT_FINISHED', 'description' => ''),
        56 => array('libxml_constant' => 'XML_ERR_XMLDECL_NOT_STARTED', 'description' => ''),
        57 => array('libxml_constant' => 'XML_ERR_XMLDECL_NOT_FINISHED', 'description' => ''),
        58 => array('libxml_constant' => 'XML_ERR_CONDSEC_NOT_STARTED', 'description' => ''),
        59 => array('libxml_constant' => 'XML_ERR_CONDSEC_NOT_FINISHED', 'description' => ''),
        60 => array('libxml_constant' => 'XML_ERR_EXT_SUBSET_NOT_FINISHED', 'description' => ''),
        61 => array('libxml_constant' => 'XML_ERR_DOCTYPE_NOT_FINISHED', 'description' => ''),
        62 => array('libxml_constant' => 'XML_ERR_MISPLACED_CDATA_END', 'description' => ''),
        63 => array('libxml_constant' => 'XML_ERR_CDATA_NOT_FINISHED', 'description' => ''),
        64 => array('libxml_constant' => 'XML_ERR_RESERVED_XML_NAME', 'description' => ''),
        65 => array('libxml_constant' => 'XML_ERR_SPACE_REQUIRED', 'description' => ''),
        66 => array('libxml_constant' => 'XML_ERR_SEPARATOR_REQUIRED', 'description' => ''),
        67 => array('libxml_constant' => 'XML_ERR_NMTOKEN_REQUIRED', 'description' => ''),
        68 => array('libxml_constant' => 'XML_ERR_NAME_REQUIRED', 'description' => ''),
        69 => array('libxml_constant' => 'XML_ERR_PCDATA_REQUIRED', 'description' => ''),
        70 => array('libxml_constant' => 'XML_ERR_URI_REQUIRED', 'description' => ''),
        71 => array('libxml_constant' => 'XML_ERR_PUBID_REQUIRED', 'description' => ''),
        72 => array('libxml_constant' => 'XML_ERR_LT_REQUIRED', 'description' => ''),
        73 => array('libxml_constant' => 'XML_ERR_GT_REQUIRED', 'description' => ''),
        74 => array('libxml_constant' => 'XML_ERR_LTSLASH_REQUIRED', 'description' => ''),
        75 => array('libxml_constant' => 'XML_ERR_EQUAL_REQUIRED', 'description' => ''),
        76 => array('libxml_constant' => 'XML_ERR_TAG_NAME_MISMATCH', 'description' => ''),
        77 => array('libxml_constant' => 'XML_ERR_TAG_NOT_FINISHED', 'description' => ''),
        78 => array('libxml_constant' => 'XML_ERR_STANDALONE_VALUE', 'description' => ''),
        79 => array('libxml_constant' => 'XML_ERR_ENCODING_NAME', 'description' => ''),
        80 => array('libxml_constant' => 'XML_ERR_HYPHEN_IN_COMMENT', 'description' => ''),
        81 => array('libxml_constant' => 'XML_ERR_INVALID_ENCODING', 'description' => ''),
        82 => array('libxml_constant' => 'XML_ERR_EXT_ENTITY_STANDALONE', 'description' => ''),
        83 => array('libxml_constant' => 'XML_ERR_CONDSEC_INVALID', 'description' => ''),
        84 => array('libxml_constant' => 'XML_ERR_VALUE_REQUIRED', 'description' => ''),
        85 => array('libxml_constant' => 'XML_ERR_NOT_WELL_BALANCED', 'description' => ''),
        86 => array('libxml_constant' => 'XML_ERR_EXTRA_CONTENT', 'description' => ''),
        87 => array('libxml_constant' => 'XML_ERR_ENTITY_CHAR_ERROR', 'description' => ''),
        88 => array('libxml_constant' => 'XML_ERR_ENTITY_PE_INTERNAL', 'description' => ''),
        89 => array('libxml_constant' => 'XML_ERR_ENTITY_LOOP', 'description' => ''),
        90 => array('libxml_constant' => 'XML_ERR_ENTITY_BOUNDARY', 'description' => ''),
        91 => array('libxml_constant' => 'XML_ERR_INVALID_URI', 'description' => ''),
        92 => array('libxml_constant' => 'XML_ERR_URI_FRAGMENT', 'description' => ''),
        93 => array('libxml_constant' => 'XML_WAR_CATALOG_PI', 'description' => ''),
        94 => array('libxml_constant' => 'XML_ERR_NO_DTD', 'description' => ''),
        95 => array('libxml_constant' => 'XML_ERR_CONDSEC_INVALID_KEYWORD', 'description' => ''),
        96 => array('libxml_constant' => 'XML_ERR_VERSION_MISSING', 'description' => ''),
        97 => array('libxml_constant' => 'XML_WAR_UNKNOWN_VERSION', 'description' => ''),
        98 => array('libxml_constant' => 'XML_WAR_LANG_VALUE', 'description' => ''),
        99 => array('libxml_constant' => 'XML_WAR_NS_URI', 'description' => ''),
        100 => array('libxml_constant' => 'XML_WAR_NS_URI_RELATIVE', 'description' => ''),
        101 => array('libxml_constant' => 'XML_ERR_MISSING_ENCODING', 'description' => ''),
        102 => array('libxml_constant' => 'XML_WAR_SPACE_VALUE', 'description' => ''),
        103 => array('libxml_constant' => 'XML_ERR_NOT_STANDALONE', 'description' => ''),
        104 => array('libxml_constant' => 'XML_ERR_ENTITY_PROCESSING', 'description' => ''),
        105 => array('libxml_constant' => 'XML_ERR_NOTATION_PROCESSING', 'description' => ''),
        106 => array('libxml_constant' => 'XML_WAR_NS_COLUMN', 'description' => ''),
        107 => array('libxml_constant' => 'XML_WAR_ENTITY_REDEFINED', 'description' => ''),
        108 => array('libxml_constant' => 'XML_ERR_UNKNOWN_VERSION', 'description' => ''),
        109 => array('libxml_constant' => 'XML_ERR_VERSION_MISMATCH', 'description' => ''),
        110 => array('libxml_constant' => 'XML_ERR_NAME_TOO_LONG', 'description' => ''),
        200 => array('libxml_constant' => 'XML_NS_ERR_XML_NAMESPACE', 'description' => ''),
        201 => array('libxml_constant' => 'XML_NS_ERR_UNDEFINED_NAMESPACE', 'description' => ''),
        202 => array('libxml_constant' => 'XML_NS_ERR_QNAME', 'description' => ''),
        203 => array('libxml_constant' => 'XML_NS_ERR_ATTRIBUTE_REDEFINED', 'description' => ''),
        204 => array('libxml_constant' => 'XML_NS_ERR_EMPTY', 'description' => ''),
        205 => array('libxml_constant' => 'XML_NS_ERR_COLON', 'description' => ''),
        500 => array('libxml_constant' => 'XML_DTD_ATTRIBUTE_DEFAULT', 'description' => ''),
        501 => array('libxml_constant' => 'XML_DTD_ATTRIBUTE_REDEFINED', 'description' => ''),
        502 => array('libxml_constant' => 'XML_DTD_ATTRIBUTE_VALUE', 'description' => ''),
        503 => array('libxml_constant' => 'XML_DTD_CONTENT_ERROR', 'description' => ''),
        504 => array('libxml_constant' => 'XML_DTD_CONTENT_MODEL', 'description' => ''),
        505 => array('libxml_constant' => 'XML_DTD_CONTENT_NOT_DETERMINIST', 'description' => ''),
        506 => array('libxml_constant' => 'XML_DTD_DIFFERENT_PREFIX', 'description' => ''),
        507 => array('libxml_constant' => 'XML_DTD_ELEM_DEFAULT_NAMESPACE', 'description' => ''),
        508 => array('libxml_constant' => 'XML_DTD_ELEM_NAMESPACE', 'description' => ''),
        509 => array('libxml_constant' => 'XML_DTD_ELEM_REDEFINED', 'description' => ''),
        510 => array('libxml_constant' => 'XML_DTD_EMPTY_NOTATION', 'description' => ''),
        511 => array('libxml_constant' => 'XML_DTD_ENTITY_TYPE', 'description' => ''),
        512 => array('libxml_constant' => 'XML_DTD_ID_FIXED', 'description' => ''),
        513 => array('libxml_constant' => 'XML_DTD_ID_REDEFINED', 'description' => ''),
        514 => array('libxml_constant' => 'XML_DTD_ID_SUBSET', 'description' => ''),
        515 => array('libxml_constant' => 'XML_DTD_INVALID_CHILD', 'description' => ''),
        516 => array('libxml_constant' => 'XML_DTD_INVALID_DEFAULT', 'description' => ''),
        517 => array('libxml_constant' => 'XML_DTD_LOAD_ERROR', 'description' => ''),
        518 => array('libxml_constant' => 'XML_DTD_MISSING_ATTRIBUTE', 'description' => ''),
        519 => array('libxml_constant' => 'XML_DTD_MIXED_CORRUPT', 'description' => ''),
        520 => array('libxml_constant' => 'XML_DTD_MULTIPLE_ID', 'description' => ''),
        521 => array('libxml_constant' => 'XML_DTD_NO_DOC', 'description' => ''),
        522 => array('libxml_constant' => 'XML_DTD_NO_DTD', 'description' => ''),
        523 => array('libxml_constant' => 'XML_DTD_NO_ELEM_NAME', 'description' => ''),
        524 => array('libxml_constant' => 'XML_DTD_NO_PREFIX', 'description' => ''),
        525 => array('libxml_constant' => 'XML_DTD_NO_ROOT', 'description' => ''),
        526 => array('libxml_constant' => 'XML_DTD_NOTATION_REDEFINED', 'description' => ''),
        527 => array('libxml_constant' => 'XML_DTD_NOTATION_VALUE', 'description' => ''),
        528 => array('libxml_constant' => 'XML_DTD_NOT_EMPTY', 'description' => ''),
        529 => array('libxml_constant' => 'XML_DTD_NOT_PCDATA', 'description' => ''),
        530 => array('libxml_constant' => 'XML_DTD_NOT_STANDALONE', 'description' => ''),
        531 => array('libxml_constant' => 'XML_DTD_ROOT_NAME', 'description' => ''),
        532 => array('libxml_constant' => 'XML_DTD_STANDALONE_WHITE_SPACE', 'description' => ''),
        533 => array('libxml_constant' => 'XML_DTD_UNKNOWN_ATTRIBUTE', 'description' => ''),
        534 => array('libxml_constant' => 'XML_DTD_UNKNOWN_ELEM', 'description' => ''),
        535 => array('libxml_constant' => 'XML_DTD_UNKNOWN_ENTITY', 'description' => ''),
        536 => array('libxml_constant' => 'XML_DTD_UNKNOWN_ID', 'description' => ''),
        537 => array('libxml_constant' => 'XML_DTD_UNKNOWN_NOTATION', 'description' => ''),
        538 => array('libxml_constant' => 'XML_DTD_STANDALONE_DEFAULTED', 'description' => ''),
        539 => array('libxml_constant' => 'XML_DTD_XMLID_VALUE', 'description' => ''),
        540 => array('libxml_constant' => 'XML_DTD_XMLID_TYPE', 'description' => ''),
        541 => array('libxml_constant' => 'XML_DTD_DUP_TOKEN', 'description' => ''),
        800 => array('libxml_constant' => 'XML_HTML_STRUCURE_ERROR', 'description' => ''),
        801 => array('libxml_constant' => 'XML_HTML_UNKNOWN_TAG', 'description' => ''),
        1000 => array('libxml_constant' => 'XML_RNGP_ANYNAME_ATTR_ANCESTOR', 'description' => ''),
        1001 => array('libxml_constant' => 'XML_RNGP_ATTR_CONFLICT', 'description' => ''),
        1002 => array('libxml_constant' => 'XML_RNGP_ATTRIBUTE_CHILDREN', 'description' => ''),
        1003 => array('libxml_constant' => 'XML_RNGP_ATTRIBUTE_CONTENT', 'description' => ''),
        1004 => array('libxml_constant' => 'XML_RNGP_ATTRIBUTE_EMPTY', 'description' => ''),
        1005 => array('libxml_constant' => 'XML_RNGP_ATTRIBUTE_NOOP', 'description' => ''),
        1006 => array('libxml_constant' => 'XML_RNGP_CHOICE_CONTENT', 'description' => ''),
        1007 => array('libxml_constant' => 'XML_RNGP_CHOICE_EMPTY', 'description' => ''),
        1008 => array('libxml_constant' => 'XML_RNGP_CREATE_FAILURE', 'description' => ''),
        1009 => array('libxml_constant' => 'XML_RNGP_DATA_CONTENT', 'description' => ''),
        1010 => array('libxml_constant' => 'XML_RNGP_DEF_CHOICE_AND_INTERLEAVE', 'description' => ''),
        1011 => array('libxml_constant' => 'XML_RNGP_DEFINE_CREATE_FAILED', 'description' => ''),
        1012 => array('libxml_constant' => 'XML_RNGP_DEFINE_EMPTY', 'description' => ''),
        1013 => array('libxml_constant' => 'XML_RNGP_DEFINE_MISSING', 'description' => ''),
        1014 => array('libxml_constant' => 'XML_RNGP_DEFINE_NAME_MISSING', 'description' => ''),
        1015 => array('libxml_constant' => 'XML_RNGP_ELEM_CONTENT_EMPTY', 'description' => ''),
        1016 => array('libxml_constant' => 'XML_RNGP_ELEM_CONTENT_ERROR', 'description' => ''),
        1017 => array('libxml_constant' => 'XML_RNGP_ELEMENT_EMPTY', 'description' => ''),
        1018 => array('libxml_constant' => 'XML_RNGP_ELEMENT_CONTENT', 'description' => ''),
        1019 => array('libxml_constant' => 'XML_RNGP_ELEMENT_NAME', 'description' => ''),
        1020 => array('libxml_constant' => 'XML_RNGP_ELEMENT_NO_CONTENT', 'description' => ''),
        1021 => array('libxml_constant' => 'XML_RNGP_ELEM_TEXT_CONFLICT', 'description' => ''),
        1022 => array('libxml_constant' => 'XML_RNGP_EMPTY', 'description' => ''),
        1023 => array('libxml_constant' => 'XML_RNGP_EMPTY_CONSTRUCT', 'description' => ''),
        1024 => array('libxml_constant' => 'XML_RNGP_EMPTY_CONTENT', 'description' => ''),
        1025 => array('libxml_constant' => 'XML_RNGP_EMPTY_NOT_EMPTY', 'description' => ''),
        1026 => array('libxml_constant' => 'XML_RNGP_ERROR_TYPE_LIB', 'description' => ''),
        1027 => array('libxml_constant' => 'XML_RNGP_EXCEPT_EMPTY', 'description' => ''),
        1028 => array('libxml_constant' => 'XML_RNGP_EXCEPT_MISSING', 'description' => ''),
        1029 => array('libxml_constant' => 'XML_RNGP_EXCEPT_MULTIPLE', 'description' => ''),
        1030 => array('libxml_constant' => 'XML_RNGP_EXCEPT_NO_CONTENT', 'description' => ''),
        1031 => array('libxml_constant' => 'XML_RNGP_EXTERNALREF_EMTPY', 'description' => ''),
        1032 => array('libxml_constant' => 'XML_RNGP_EXTERNAL_REF_FAILURE', 'description' => ''),
        1033 => array('libxml_constant' => 'XML_RNGP_EXTERNALREF_RECURSE', 'description' => ''),
        1034 => array('libxml_constant' => 'XML_RNGP_FORBIDDEN_ATTRIBUTE', 'description' => ''),
        1035 => array('libxml_constant' => 'XML_RNGP_FOREIGN_ELEMENT', 'description' => ''),
        1036 => array('libxml_constant' => 'XML_RNGP_GRAMMAR_CONTENT', 'description' => ''),
        1037 => array('libxml_constant' => 'XML_RNGP_GRAMMAR_EMPTY', 'description' => ''),
        1038 => array('libxml_constant' => 'XML_RNGP_GRAMMAR_MISSING', 'description' => ''),
        1039 => array('libxml_constant' => 'XML_RNGP_GRAMMAR_NO_START', 'description' => ''),
        1040 => array('libxml_constant' => 'XML_RNGP_GROUP_ATTR_CONFLICT', 'description' => ''),
        1041 => array('libxml_constant' => 'XML_RNGP_HREF_ERROR', 'description' => ''),
        1042 => array('libxml_constant' => 'XML_RNGP_INCLUDE_EMPTY', 'description' => ''),
        1043 => array('libxml_constant' => 'XML_RNGP_INCLUDE_FAILURE', 'description' => ''),
        1044 => array('libxml_constant' => 'XML_RNGP_INCLUDE_RECURSE', 'description' => ''),
        1045 => array('libxml_constant' => 'XML_RNGP_INTERLEAVE_ADD', 'description' => ''),
        1046 => array('libxml_constant' => 'XML_RNGP_INTERLEAVE_CREATE_FAILED', 'description' => ''),
        1047 => array('libxml_constant' => 'XML_RNGP_INTERLEAVE_EMPTY', 'description' => ''),
        1048 => array('libxml_constant' => 'XML_RNGP_INTERLEAVE_NO_CONTENT', 'description' => ''),
        1049 => array('libxml_constant' => 'XML_RNGP_INVALID_DEFINE_NAME', 'description' => ''),
        1050 => array('libxml_constant' => 'XML_RNGP_INVALID_URI', 'description' => ''),
        1051 => array('libxml_constant' => 'XML_RNGP_INVALID_VALUE', 'description' => ''),
        1052 => array('libxml_constant' => 'XML_RNGP_MISSING_HREF', 'description' => ''),
        1053 => array('libxml_constant' => 'XML_RNGP_NAME_MISSING', 'description' => ''),
        1054 => array('libxml_constant' => 'XML_RNGP_NEED_COMBINE', 'description' => ''),
        1055 => array('libxml_constant' => 'XML_RNGP_NOTALLOWED_NOT_EMPTY', 'description' => ''),
        1056 => array('libxml_constant' => 'XML_RNGP_NSNAME_ATTR_ANCESTOR', 'description' => ''),
        1057 => array('libxml_constant' => 'XML_RNGP_NSNAME_NO_NS', 'description' => ''),
        1058 => array('libxml_constant' => 'XML_RNGP_PARAM_FORBIDDEN', 'description' => ''),
        1059 => array('libxml_constant' => 'XML_RNGP_PARAM_NAME_MISSING', 'description' => ''),
        1060 => array('libxml_constant' => 'XML_RNGP_PARENTREF_CREATE_FAILED', 'description' => ''),
        1061 => array('libxml_constant' => 'XML_RNGP_PARENTREF_NAME_INVALID', 'description' => ''),
        1062 => array('libxml_constant' => 'XML_RNGP_PARENTREF_NO_NAME', 'description' => ''),
        1063 => array('libxml_constant' => 'XML_RNGP_PARENTREF_NO_PARENT', 'description' => ''),
        1064 => array('libxml_constant' => 'XML_RNGP_PARENTREF_NOT_EMPTY', 'description' => ''),
        1065 => array('libxml_constant' => 'XML_RNGP_PARSE_ERROR', 'description' => ''),
        1066 => array('libxml_constant' => 'XML_RNGP_PAT_ANYNAME_EXCEPT_ANYNAME', 'description' => ''),
        1067 => array('libxml_constant' => 'XML_RNGP_PAT_ATTR_ATTR', 'description' => ''),
        1068 => array('libxml_constant' => 'XML_RNGP_PAT_ATTR_ELEM', 'description' => ''),
        1069 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_ATTR', 'description' => ''),
        1070 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_ELEM', 'description' => ''),
        1071 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_EMPTY', 'description' => ''),
        1072 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_GROUP', 'description' => ''),
        1073 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_INTERLEAVE', 'description' => ''),
        1074 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_LIST', 'description' => ''),
        1075 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_ONEMORE', 'description' => ''),
        1076 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_REF', 'description' => ''),
        1077 => array('libxml_constant' => 'XML_RNGP_PAT_DATA_EXCEPT_TEXT', 'description' => ''),
        1078 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_ATTR', 'description' => ''),
        1079 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_ELEM', 'description' => ''),
        1080 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_INTERLEAVE', 'description' => ''),
        1081 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_LIST', 'description' => ''),
        1082 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_REF', 'description' => ''),
        1083 => array('libxml_constant' => 'XML_RNGP_PAT_LIST_TEXT', 'description' => ''),
        1084 => array('libxml_constant' => 'XML_RNGP_PAT_NSNAME_EXCEPT_ANYNAME', 'description' => ''),
        1085 => array('libxml_constant' => 'XML_RNGP_PAT_NSNAME_EXCEPT_NSNAME', 'description' => ''),
        1086 => array('libxml_constant' => 'XML_RNGP_PAT_ONEMORE_GROUP_ATTR', 'description' => ''),
        1087 => array('libxml_constant' => 'XML_RNGP_PAT_ONEMORE_INTERLEAVE_ATTR', 'description' => ''),
        1088 => array('libxml_constant' => 'XML_RNGP_PAT_START_ATTR', 'description' => ''),
        1089 => array('libxml_constant' => 'XML_RNGP_PAT_START_DATA', 'description' => ''),
        1090 => array('libxml_constant' => 'XML_RNGP_PAT_START_EMPTY', 'description' => ''),
        1091 => array('libxml_constant' => 'XML_RNGP_PAT_START_GROUP', 'description' => ''),
        1092 => array('libxml_constant' => 'XML_RNGP_PAT_START_INTERLEAVE', 'description' => ''),
        1093 => array('libxml_constant' => 'XML_RNGP_PAT_START_LIST', 'description' => ''),
        1094 => array('libxml_constant' => 'XML_RNGP_PAT_START_ONEMORE', 'description' => ''),
        1095 => array('libxml_constant' => 'XML_RNGP_PAT_START_TEXT', 'description' => ''),
        1096 => array('libxml_constant' => 'XML_RNGP_PAT_START_VALUE', 'description' => ''),
        1097 => array('libxml_constant' => 'XML_RNGP_PREFIX_UNDEFINED', 'description' => ''),
        1098 => array('libxml_constant' => 'XML_RNGP_REF_CREATE_FAILED', 'description' => ''),
        1099 => array('libxml_constant' => 'XML_RNGP_REF_CYCLE', 'description' => ''),
        1100 => array('libxml_constant' => 'XML_RNGP_REF_NAME_INVALID', 'description' => ''),
        1101 => array('libxml_constant' => 'XML_RNGP_REF_NO_DEF', 'description' => ''),
        1102 => array('libxml_constant' => 'XML_RNGP_REF_NO_NAME', 'description' => ''),
        1103 => array('libxml_constant' => 'XML_RNGP_REF_NOT_EMPTY', 'description' => ''),
        1104 => array('libxml_constant' => 'XML_RNGP_START_CHOICE_AND_INTERLEAVE', 'description' => ''),
        1105 => array('libxml_constant' => 'XML_RNGP_START_CONTENT', 'description' => ''),
        1106 => array('libxml_constant' => 'XML_RNGP_START_EMPTY', 'description' => ''),
        1107 => array('libxml_constant' => 'XML_RNGP_START_MISSING', 'description' => ''),
        1108 => array('libxml_constant' => 'XML_RNGP_TEXT_EXPECTED', 'description' => ''),
        1109 => array('libxml_constant' => 'XML_RNGP_TEXT_HAS_CHILD', 'description' => ''),
        1110 => array('libxml_constant' => 'XML_RNGP_TYPE_MISSING', 'description' => ''),
        1111 => array('libxml_constant' => 'XML_RNGP_TYPE_NOT_FOUND', 'description' => ''),
        1112 => array('libxml_constant' => 'XML_RNGP_TYPE_VALUE', 'description' => ''),
        1113 => array('libxml_constant' => 'XML_RNGP_UNKNOWN_ATTRIBUTE', 'description' => ''),
        1114 => array('libxml_constant' => 'XML_RNGP_UNKNOWN_COMBINE', 'description' => ''),
        1115 => array('libxml_constant' => 'XML_RNGP_UNKNOWN_CONSTRUCT', 'description' => ''),
        1116 => array('libxml_constant' => 'XML_RNGP_UNKNOWN_TYPE_LIB', 'description' => ''),
        1117 => array('libxml_constant' => 'XML_RNGP_URI_FRAGMENT', 'description' => ''),
        1118 => array('libxml_constant' => 'XML_RNGP_URI_NOT_ABSOLUTE', 'description' => ''),
        1119 => array('libxml_constant' => 'XML_RNGP_VALUE_EMPTY', 'description' => ''),
        1120 => array('libxml_constant' => 'XML_RNGP_VALUE_NO_CONTENT', 'description' => ''),
        1121 => array('libxml_constant' => 'XML_RNGP_XMLNS_NAME', 'description' => ''),
        1122 => array('libxml_constant' => 'XML_RNGP_XML_NS', 'description' => ''),
        1200 => array('libxml_constant' => 'XML_XPATH_EXPRESSION_OK', 'description' => ''),
        1201 => array('libxml_constant' => 'XML_XPATH_NUMBER_ERROR', 'description' => ''),
        1202 => array('libxml_constant' => 'XML_XPATH_UNFINISHED_LITERAL_ERROR', 'description' => ''),
        1203 => array('libxml_constant' => 'XML_XPATH_START_LITERAL_ERROR', 'description' => ''),
        1204 => array('libxml_constant' => 'XML_XPATH_VARIABLE_REF_ERROR', 'description' => ''),
        1205 => array('libxml_constant' => 'XML_XPATH_UNDEF_VARIABLE_ERROR', 'description' => ''),
        1206 => array('libxml_constant' => 'XML_XPATH_INVALID_PREDICATE_ERROR', 'description' => ''),
        1207 => array('libxml_constant' => 'XML_XPATH_EXPR_ERROR', 'description' => ''),
        1208 => array('libxml_constant' => 'XML_XPATH_UNCLOSED_ERROR', 'description' => ''),
        1209 => array('libxml_constant' => 'XML_XPATH_UNKNOWN_FUNC_ERROR', 'description' => ''),
        1210 => array('libxml_constant' => 'XML_XPATH_INVALID_OPERAND', 'description' => ''),
        1211 => array('libxml_constant' => 'XML_XPATH_INVALID_TYPE', 'description' => ''),
        1212 => array('libxml_constant' => 'XML_XPATH_INVALID_ARITY', 'description' => ''),
        1213 => array('libxml_constant' => 'XML_XPATH_INVALID_CTXT_SIZE', 'description' => ''),
        1214 => array('libxml_constant' => 'XML_XPATH_INVALID_CTXT_POSITION', 'description' => ''),
        1215 => array('libxml_constant' => 'XML_XPATH_MEMORY_ERROR', 'description' => ''),
        1216 => array('libxml_constant' => 'XML_XPTR_SYNTAX_ERROR', 'description' => ''),
        1217 => array('libxml_constant' => 'XML_XPTR_RESOURCE_ERROR', 'description' => ''),
        1218 => array('libxml_constant' => 'XML_XPTR_SUB_RESOURCE_ERROR', 'description' => ''),
        1219 => array('libxml_constant' => 'XML_XPATH_UNDEF_PREFIX_ERROR', 'description' => ''),
        1220 => array('libxml_constant' => 'XML_XPATH_ENCODING_ERROR', 'description' => ''),
        1221 => array('libxml_constant' => 'XML_XPATH_INVALID_CHAR_ERROR', 'description' => ''),
        1300 => array('libxml_constant' => 'XML_TREE_INVALID_HEX', 'description' => ''),
        1301 => array('libxml_constant' => 'XML_TREE_INVALID_DEC', 'description' => ''),
        1302 => array('libxml_constant' => 'XML_TREE_UNTERMINATED_ENTITY', 'description' => ''),
        1303 => array('libxml_constant' => 'XML_TREE_NOT_UTF8', 'description' => ''),
        1400 => array('libxml_constant' => 'XML_SAVE_NOT_UTF8', 'description' => ''),
        1401 => array('libxml_constant' => 'XML_SAVE_CHAR_INVALID', 'description' => ''),
        1402 => array('libxml_constant' => 'XML_SAVE_NO_DOCTYPE', 'description' => ''),
        1403 => array('libxml_constant' => 'XML_SAVE_UNKNOWN_ENCODING', 'description' => ''),
        1450 => array('libxml_constant' => 'XML_REGEXP_COMPILE_ERROR', 'description' => ''),
        1500 => array('libxml_constant' => 'XML_IO_UNKNOWN', 'description' => ''),
        1501 => array('libxml_constant' => 'XML_IO_EACCES', 'description' => ''),
        1502 => array('libxml_constant' => 'XML_IO_EAGAIN', 'description' => ''),
        1503 => array('libxml_constant' => 'XML_IO_EBADF', 'description' => ''),
        1504 => array('libxml_constant' => 'XML_IO_EBADMSG', 'description' => ''),
        1505 => array('libxml_constant' => 'XML_IO_EBUSY', 'description' => ''),
        1506 => array('libxml_constant' => 'XML_IO_ECANCELED', 'description' => ''),
        1507 => array('libxml_constant' => 'XML_IO_ECHILD', 'description' => ''),
        1508 => array('libxml_constant' => 'XML_IO_EDEADLK', 'description' => ''),
        1509 => array('libxml_constant' => 'XML_IO_EDOM', 'description' => ''),
        1510 => array('libxml_constant' => 'XML_IO_EEXIST', 'description' => ''),
        1511 => array('libxml_constant' => 'XML_IO_EFAULT', 'description' => ''),
        1512 => array('libxml_constant' => 'XML_IO_EFBIG', 'description' => ''),
        1513 => array('libxml_constant' => 'XML_IO_EINPROGRESS', 'description' => ''),
        1514 => array('libxml_constant' => 'XML_IO_EINTR', 'description' => ''),
        1515 => array('libxml_constant' => 'XML_IO_EINVAL', 'description' => ''),
        1516 => array('libxml_constant' => 'XML_IO_EIO', 'description' => ''),
        1517 => array('libxml_constant' => 'XML_IO_EISDIR', 'description' => ''),
        1518 => array('libxml_constant' => 'XML_IO_EMFILE', 'description' => ''),
        1519 => array('libxml_constant' => 'XML_IO_EMLINK', 'description' => ''),
        1520 => array('libxml_constant' => 'XML_IO_EMSGSIZE', 'description' => ''),
        1521 => array('libxml_constant' => 'XML_IO_ENAMETOOLONG', 'description' => ''),
        1522 => array('libxml_constant' => 'XML_IO_ENFILE', 'description' => ''),
        1523 => array('libxml_constant' => 'XML_IO_ENODEV', 'description' => ''),
        1524 => array('libxml_constant' => 'XML_IO_ENOENT', 'description' => ''),
        1525 => array('libxml_constant' => 'XML_IO_ENOEXEC', 'description' => ''),
        1526 => array('libxml_constant' => 'XML_IO_ENOLCK', 'description' => ''),
        1527 => array('libxml_constant' => 'XML_IO_ENOMEM', 'description' => ''),
        1528 => array('libxml_constant' => 'XML_IO_ENOSPC', 'description' => ''),
        1529 => array('libxml_constant' => 'XML_IO_ENOSYS', 'description' => ''),
        1530 => array('libxml_constant' => 'XML_IO_ENOTDIR', 'description' => ''),
        1531 => array('libxml_constant' => 'XML_IO_ENOTEMPTY', 'description' => ''),
        1532 => array('libxml_constant' => 'XML_IO_ENOTSUP', 'description' => ''),
        1533 => array('libxml_constant' => 'XML_IO_ENOTTY', 'description' => ''),
        1534 => array('libxml_constant' => 'XML_IO_ENXIO', 'description' => ''),
        1535 => array('libxml_constant' => 'XML_IO_EPERM', 'description' => ''),
        1536 => array('libxml_constant' => 'XML_IO_EPIPE', 'description' => ''),
        1537 => array('libxml_constant' => 'XML_IO_ERANGE', 'description' => ''),
        1538 => array('libxml_constant' => 'XML_IO_EROFS', 'description' => ''),
        1539 => array('libxml_constant' => 'XML_IO_ESPIPE', 'description' => ''),
        1540 => array('libxml_constant' => 'XML_IO_ESRCH', 'description' => ''),
        1541 => array('libxml_constant' => 'XML_IO_ETIMEDOUT', 'description' => ''),
        1542 => array('libxml_constant' => 'XML_IO_EXDEV', 'description' => ''),
        1543 => array('libxml_constant' => 'XML_IO_NETWORK_ATTEMPT', 'description' => ''),
        1544 => array('libxml_constant' => 'XML_IO_ENCODER', 'description' => ''),
        1545 => array('libxml_constant' => 'XML_IO_FLUSH', 'description' => ''),
        1546 => array('libxml_constant' => 'XML_IO_WRITE', 'description' => ''),
        1547 => array('libxml_constant' => 'XML_IO_NO_INPUT', 'description' => ''),
        1548 => array('libxml_constant' => 'XML_IO_BUFFER_FULL', 'description' => ''),
        1549 => array('libxml_constant' => 'XML_IO_LOAD_ERROR', 'description' => ''),
        1550 => array('libxml_constant' => 'XML_IO_ENOTSOCK', 'description' => ''),
        1551 => array('libxml_constant' => 'XML_IO_EISCONN', 'description' => ''),
        1552 => array('libxml_constant' => 'XML_IO_ECONNREFUSED', 'description' => ''),
        1553 => array('libxml_constant' => 'XML_IO_ENETUNREACH', 'description' => ''),
        1554 => array('libxml_constant' => 'XML_IO_EADDRINUSE', 'description' => ''),
        1555 => array('libxml_constant' => 'XML_IO_EALREADY', 'description' => ''),
        1556 => array('libxml_constant' => 'XML_IO_EAFNOSUPPORT', 'description' => ''),
        1600 => array('libxml_constant' => 'XML_XINCLUDE_RECURSION', 'description' => ''),
        1601 => array('libxml_constant' => 'XML_XINCLUDE_PARSE_VALUE', 'description' => ''),
        1602 => array('libxml_constant' => 'XML_XINCLUDE_ENTITY_DEF_MISMATCH', 'description' => ''),
        1603 => array('libxml_constant' => 'XML_XINCLUDE_NO_HREF', 'description' => ''),
        1604 => array('libxml_constant' => 'XML_XINCLUDE_NO_FALLBACK', 'description' => ''),
        1605 => array('libxml_constant' => 'XML_XINCLUDE_HREF_URI', 'description' => ''),
        1606 => array('libxml_constant' => 'XML_XINCLUDE_TEXT_FRAGMENT', 'description' => ''),
        1607 => array('libxml_constant' => 'XML_XINCLUDE_TEXT_DOCUMENT', 'description' => ''),
        1608 => array('libxml_constant' => 'XML_XINCLUDE_INVALID_CHAR', 'description' => ''),
        1609 => array('libxml_constant' => 'XML_XINCLUDE_BUILD_FAILED', 'description' => ''),
        1610 => array('libxml_constant' => 'XML_XINCLUDE_UNKNOWN_ENCODING', 'description' => ''),
        1611 => array('libxml_constant' => 'XML_XINCLUDE_MULTIPLE_ROOT', 'description' => ''),
        1612 => array('libxml_constant' => 'XML_XINCLUDE_XPTR_FAILED', 'description' => ''),
        1613 => array('libxml_constant' => 'XML_XINCLUDE_XPTR_RESULT', 'description' => ''),
        1614 => array('libxml_constant' => 'XML_XINCLUDE_INCLUDE_IN_INCLUDE', 'description' => ''),
        1615 => array('libxml_constant' => 'XML_XINCLUDE_FALLBACKS_IN_INCLUDE', 'description' => ''),
        1616 => array('libxml_constant' => 'XML_XINCLUDE_FALLBACK_NOT_IN_INCLUDE', 'description' => ''),
        1617 => array('libxml_constant' => 'XML_XINCLUDE_DEPRECATED_NS', 'description' => ''),
        1618 => array('libxml_constant' => 'XML_XINCLUDE_FRAGMENT_ID', 'description' => ''),
        1650 => array('libxml_constant' => 'XML_CATALOG_MISSING_ATTR', 'description' => ''),
        1651 => array('libxml_constant' => 'XML_CATALOG_ENTRY_BROKEN', 'description' => ''),
        1652 => array('libxml_constant' => 'XML_CATALOG_PREFER_VALUE', 'description' => ''),
        1653 => array('libxml_constant' => 'XML_CATALOG_NOT_CATALOG', 'description' => ''),
        1654 => array('libxml_constant' => 'XML_CATALOG_RECURSION', 'description' => ''),
        1700 => array('libxml_constant' => 'XML_SCHEMAP_PREFIX_UNDEFINED', 'description' => ''),
        1701 => array('libxml_constant' => 'XML_SCHEMAP_ATTRFORMDEFAULT_VALUE', 'description' => ''),
        1702 => array('libxml_constant' => 'XML_SCHEMAP_ATTRGRP_NONAME_NOREF', 'description' => ''),
        1703 => array('libxml_constant' => 'XML_SCHEMAP_ATTR_NONAME_NOREF', 'description' => ''),
        1704 => array('libxml_constant' => 'XML_SCHEMAP_COMPLEXTYPE_NONAME_NOREF', 'description' => ''),
        1705 => array('libxml_constant' => 'XML_SCHEMAP_ELEMFORMDEFAULT_VALUE', 'description' => ''),
        1706 => array('libxml_constant' => 'XML_SCHEMAP_ELEM_NONAME_NOREF', 'description' => ''),
        1707 => array('libxml_constant' => 'XML_SCHEMAP_EXTENSION_NO_BASE', 'description' => ''),
        1708 => array('libxml_constant' => 'XML_SCHEMAP_FACET_NO_VALUE', 'description' => ''),
        1709 => array('libxml_constant' => 'XML_SCHEMAP_FAILED_BUILD_IMPORT', 'description' => ''),
        1710 => array('libxml_constant' => 'XML_SCHEMAP_GROUP_NONAME_NOREF', 'description' => ''),
        1711 => array('libxml_constant' => 'XML_SCHEMAP_IMPORT_NAMESPACE_NOT_URI', 'description' => ''),
        1712 => array('libxml_constant' => 'XML_SCHEMAP_IMPORT_REDEFINE_NSNAME', 'description' => ''),
        1713 => array('libxml_constant' => 'XML_SCHEMAP_IMPORT_SCHEMA_NOT_URI', 'description' => ''),
        1714 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_BOOLEAN', 'description' => ''),
        1715 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_ENUM', 'description' => ''),
        1716 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_FACET', 'description' => ''),
        1717 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_FACET_VALUE', 'description' => ''),
        1718 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_MAXOCCURS', 'description' => ''),
        1719 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_MINOCCURS', 'description' => ''),
        1720 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_REF_AND_SUBTYPE', 'description' => ''),
        1721 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_WHITE_SPACE', 'description' => ''),
        1722 => array('libxml_constant' => 'XML_SCHEMAP_NOATTR_NOREF', 'description' => ''),
        1723 => array('libxml_constant' => 'XML_SCHEMAP_NOTATION_NO_NAME', 'description' => ''),
        1724 => array('libxml_constant' => 'XML_SCHEMAP_NOTYPE_NOREF', 'description' => ''),
        1725 => array('libxml_constant' => 'XML_SCHEMAP_REF_AND_SUBTYPE', 'description' => ''),
        1726 => array('libxml_constant' => 'XML_SCHEMAP_RESTRICTION_NONAME_NOREF', 'description' => ''),
        1727 => array('libxml_constant' => 'XML_SCHEMAP_SIMPLETYPE_NONAME', 'description' => ''),
        1728 => array('libxml_constant' => 'XML_SCHEMAP_TYPE_AND_SUBTYPE', 'description' => ''),
        1729 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ALL_CHILD', 'description' => ''),
        1730 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ANYATTRIBUTE_CHILD', 'description' => ''),
        1731 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ATTR_CHILD', 'description' => ''),
        1732 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ATTRGRP_CHILD', 'description' => ''),
        1733 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ATTRIBUTE_GROUP', 'description' => ''),
        1734 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_BASE_TYPE', 'description' => ''),
        1735 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_CHOICE_CHILD', 'description' => ''),
        1736 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_COMPLEXCONTENT_CHILD', 'description' => ''),
        1737 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_COMPLEXTYPE_CHILD', 'description' => ''),
        1738 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_ELEM_CHILD', 'description' => ''),
        1739 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_EXTENSION_CHILD', 'description' => ''),
        1740 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_FACET_CHILD', 'description' => ''),
        1741 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_FACET_TYPE', 'description' => ''),
        1742 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_GROUP_CHILD', 'description' => ''),
        1743 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_IMPORT_CHILD', 'description' => ''),
        1744 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_LIST_CHILD', 'description' => ''),
        1745 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_NOTATION_CHILD', 'description' => ''),
        1746 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_PROCESSCONTENT_CHILD', 'description' => ''),
        1747 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_REF', 'description' => ''),
        1748 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_RESTRICTION_CHILD', 'description' => ''),
        1749 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_SCHEMAS_CHILD', 'description' => ''),
        1750 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_SEQUENCE_CHILD', 'description' => ''),
        1751 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_SIMPLECONTENT_CHILD', 'description' => ''),
        1752 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_SIMPLETYPE_CHILD', 'description' => ''),
        1753 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_TYPE', 'description' => ''),
        1754 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_UNION_CHILD', 'description' => ''),
        1755 => array('libxml_constant' => 'XML_SCHEMAP_ELEM_DEFAULT_FIXED', 'description' => ''),
        1756 => array('libxml_constant' => 'XML_SCHEMAP_REGEXP_INVALID', 'description' => ''),
        1757 => array('libxml_constant' => 'XML_SCHEMAP_FAILED_LOAD', 'description' => ''),
        1758 => array('libxml_constant' => 'XML_SCHEMAP_NOTHING_TO_PARSE', 'description' => ''),
        1759 => array('libxml_constant' => 'XML_SCHEMAP_NOROOT', 'description' => ''),
        1760 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_GROUP', 'description' => ''),
        1761 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_TYPE', 'description' => ''),
        1762 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_ELEMENT', 'description' => ''),
        1763 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_ATTRGROUP', 'description' => ''),
        1764 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_ATTR', 'description' => ''),
        1765 => array('libxml_constant' => 'XML_SCHEMAP_REDEFINED_NOTATION', 'description' => ''),
        1766 => array('libxml_constant' => 'XML_SCHEMAP_FAILED_PARSE', 'description' => ''),
        1767 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_PREFIX', 'description' => ''),
        1768 => array('libxml_constant' => 'XML_SCHEMAP_DEF_AND_PREFIX', 'description' => ''),
        1769 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_INCLUDE_CHILD', 'description' => ''),
        1770 => array('libxml_constant' => 'XML_SCHEMAP_INCLUDE_SCHEMA_NOT_URI', 'description' => ''),
        1771 => array('libxml_constant' => 'XML_SCHEMAP_INCLUDE_SCHEMA_NO_URI', 'description' => ''),
        1772 => array('libxml_constant' => 'XML_SCHEMAP_NOT_SCHEMA', 'description' => ''),
        1773 => array('libxml_constant' => 'XML_SCHEMAP_UNKNOWN_MEMBER_TYPE', 'description' => ''),
        1774 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_ATTR_USE', 'description' => ''),
        1775 => array('libxml_constant' => 'XML_SCHEMAP_RECURSIVE', 'description' => ''),
        1776 => array('libxml_constant' => 'XML_SCHEMAP_SUPERNUMEROUS_LIST_ITEM_TYPE', 'description' => ''),
        1777 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_ATTR_COMBINATION', 'description' => ''),
        1778 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_ATTR_INLINE_COMBINATION', 'description' => ''),
        1779 => array('libxml_constant' => 'XML_SCHEMAP_MISSING_SIMPLETYPE_CHILD', 'description' => ''),
        1780 => array('libxml_constant' => 'XML_SCHEMAP_INVALID_ATTR_NAME', 'description' => ''),
        1781 => array('libxml_constant' => 'XML_SCHEMAP_REF_AND_CONTENT', 'description' => ''),
        1782 => array('libxml_constant' => 'XML_SCHEMAP_CT_PROPS_CORRECT_1', 'description' => ''),
        1783 => array('libxml_constant' => 'XML_SCHEMAP_CT_PROPS_CORRECT_2', 'description' => ''),
        1784 => array('libxml_constant' => 'XML_SCHEMAP_CT_PROPS_CORRECT_3', 'description' => ''),
        1785 => array('libxml_constant' => 'XML_SCHEMAP_CT_PROPS_CORRECT_4', 'description' => ''),
        1786 => array('libxml_constant' => 'XML_SCHEMAP_CT_PROPS_CORRECT_5', 'description' => ''),
        1787 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_1', 'description' => ''),
        1788 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_1', 'description' => ''),
        1789 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_2', 'description' => ''),
        1790 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_2', 'description' => ''),
        1791 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_3', 'description' => ''),
        1792 => array('libxml_constant' => 'XML_SCHEMAP_WILDCARD_INVALID_NS_MEMBER', 'description' => ''),
        1793 => array('libxml_constant' => 'XML_SCHEMAP_INTERSECTION_NOT_EXPRESSIBLE', 'description' => ''),
        1794 => array('libxml_constant' => 'XML_SCHEMAP_UNION_NOT_EXPRESSIBLE', 'description' => ''),
        1795 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_3_1', 'description' => ''),
        1796 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_3_2', 'description' => ''),
        1797 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_1', 'description' => ''),
        1798 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_2', 'description' => ''),
        1799 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_3', 'description' => ''),
        1800 => array('libxml_constant' => 'XML_SCHEMAP_COS_CT_EXTENDS_1_3', 'description' => ''),
        1801 => array('libxml_constant' => 'XML_SCHEMAV_NOROOT', 'description' => ''),
        1802 => array('libxml_constant' => 'XML_SCHEMAV_UNDECLAREDELEM', 'description' => ''),
        1803 => array('libxml_constant' => 'XML_SCHEMAV_NOTTOPLEVEL', 'description' => ''),
        1804 => array('libxml_constant' => 'XML_SCHEMAV_MISSING', 'description' => ''),
        1805 => array('libxml_constant' => 'XML_SCHEMAV_WRONGELEM', 'description' => ''),
        1806 => array('libxml_constant' => 'XML_SCHEMAV_NOTYPE', 'description' => ''),
        1807 => array('libxml_constant' => 'XML_SCHEMAV_NOROLLBACK', 'description' => ''),
        1808 => array('libxml_constant' => 'XML_SCHEMAV_ISABSTRACT', 'description' => ''),
        1809 => array('libxml_constant' => 'XML_SCHEMAV_NOTEMPTY', 'description' => ''),
        1810 => array('libxml_constant' => 'XML_SCHEMAV_ELEMCONT', 'description' => ''),
        1811 => array('libxml_constant' => 'XML_SCHEMAV_HAVEDEFAULT', 'description' => ''),
        1812 => array('libxml_constant' => 'XML_SCHEMAV_NOTNILLABLE', 'description' => ''),
        1813 => array('libxml_constant' => 'XML_SCHEMAV_EXTRACONTENT', 'description' => ''),
        1814 => array('libxml_constant' => 'XML_SCHEMAV_INVALIDATTR', 'description' => ''),
        1815 => array('libxml_constant' => 'XML_SCHEMAV_INVALIDELEM', 'description' => ''),
        1816 => array('libxml_constant' => 'XML_SCHEMAV_NOTDETERMINIST', 'description' => ''),
        1817 => array('libxml_constant' => 'XML_SCHEMAV_CONSTRUCT', 'description' => ''),
        1818 => array('libxml_constant' => 'XML_SCHEMAV_INTERNAL', 'description' => ''),
        1819 => array('libxml_constant' => 'XML_SCHEMAV_NOTSIMPLE', 'description' => ''),
        1820 => array('libxml_constant' => 'XML_SCHEMAV_ATTRUNKNOWN', 'description' => ''),
        1821 => array('libxml_constant' => 'XML_SCHEMAV_ATTRINVALID', 'description' => ''),
        1822 => array('libxml_constant' => 'XML_SCHEMAV_VALUE', 'description' => ''),
        1823 => array('libxml_constant' => 'XML_SCHEMAV_FACET', 'description' => ''),
        1824 => array('libxml_constant' => 'XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_1', 'description' => 'Invalid value for the type'),
        1825 => array('libxml_constant' => 'XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_2', 'description' => ''),
        1826 => array('libxml_constant' => 'XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_3', 'description' => ''),
        1827 => array('libxml_constant' => 'XML_SCHEMAV_CVC_TYPE_3_1_1', 'description' => ''),
        1828 => array('libxml_constant' => 'XML_SCHEMAV_CVC_TYPE_3_1_2', 'description' => ''),
        1829 => array('libxml_constant' => 'XML_SCHEMAV_CVC_FACET_VALID', 'description' => ''),
        1830 => array('libxml_constant' => 'XML_SCHEMAV_CVC_LENGTH_VALID', 'description' => ''),
        1831 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MINLENGTH_VALID', 'description' => ''),
        1832 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MAXLENGTH_VALID', 'description' => ''),
        1833 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MININCLUSIVE_VALID', 'description' => ''),
        1834 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MAXINCLUSIVE_VALID', 'description' => ''),
        1835 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MINEXCLUSIVE_VALID', 'description' => ''),
        1836 => array('libxml_constant' => 'XML_SCHEMAV_CVC_MAXEXCLUSIVE_VALID', 'description' => ''),
        1837 => array('libxml_constant' => 'XML_SCHEMAV_CVC_TOTALDIGITS_VALID', 'description' => ''),
        1838 => array('libxml_constant' => 'XML_SCHEMAV_CVC_FRACTIONDIGITS_VALID', 'description' => ''),
        1839 => array('libxml_constant' => 'XML_SCHEMAV_CVC_PATTERN_VALID', 'description' => ''),
        1840 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ENUMERATION_VALID', 'description' => 'Value not in the set'),
        1841 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_2_1', 'description' => ''),
        1842 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_2_2', 'description' => ''),
        1843 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_2_3', 'description' => ''),
        1844 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_2_4', 'description' => ''),
        1845 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_1', 'description' => ''),
        1846 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_2', 'description' => ''),
        1847 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_3_1', 'description' => ''),
        1848 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_3_2_1', 'description' => ''),
        1849 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_3_2_2', 'description' => ''),
        1850 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_4_1', 'description' => ''),
        1851 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_4_2', 'description' => ''),
        1852 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_4_3', 'description' => ''),
        1853 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_1_1', 'description' => ''),
        1854 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_1_2', 'description' => ''),
        1855 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_2_1', 'description' => ''),
        1856 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_2_2_1', 'description' => ''),
        1857 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_2_2_2_1', 'description' => ''),
        1858 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_5_2_2_2_2', 'description' => ''),
        1859 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_6', 'description' => ''),
        1860 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ELT_7', 'description' => ''),
        1861 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ATTRIBUTE_1', 'description' => ''),
        1862 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ATTRIBUTE_2', 'description' => ''),
        1863 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ATTRIBUTE_3', 'description' => ''),
        1864 => array('libxml_constant' => 'XML_SCHEMAV_CVC_ATTRIBUTE_4', 'description' => ''),
        1865 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_3_1', 'description' => ''),
        1866 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_3_2_1', 'description' => ''),
        1867 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_3_2_2', 'description' => ''),
        1868 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_4', 'description' => ''),
        1869 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_5_1', 'description' => ''),
        1870 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_5_2', 'description' => ''),
        1871 => array('libxml_constant' => 'XML_SCHEMAV_ELEMENT_CONTENT', 'description' => ''),
        1872 => array('libxml_constant' => 'XML_SCHEMAV_DOCUMENT_ELEMENT_MISSING', 'description' => ''),
        1873 => array('libxml_constant' => 'XML_SCHEMAV_CVC_COMPLEX_TYPE_1', 'description' => ''),
        1874 => array('libxml_constant' => 'XML_SCHEMAV_CVC_AU', 'description' => ''),
        1875 => array('libxml_constant' => 'XML_SCHEMAV_CVC_TYPE_1', 'description' => ''),
        1876 => array('libxml_constant' => 'XML_SCHEMAV_CVC_TYPE_2', 'description' => ''),
        1877 => array('libxml_constant' => 'XML_SCHEMAV_CVC_IDC', 'description' => ''),
        1878 => array('libxml_constant' => 'XML_SCHEMAV_CVC_WILDCARD', 'description' => ''),
        1879 => array('libxml_constant' => 'XML_SCHEMAV_MISC', 'description' => ''),
        1900 => array('libxml_constant' => 'XML_XPTR_UNKNOWN_SCHEME', 'description' => ''),
        1901 => array('libxml_constant' => 'XML_XPTR_CHILDSEQ_START', 'description' => ''),
        1902 => array('libxml_constant' => 'XML_XPTR_EVAL_FAILED', 'description' => ''),
        1903 => array('libxml_constant' => 'XML_XPTR_EXTRA_OBJECTS', 'description' => ''),
        1950 => array('libxml_constant' => 'XML_C14N_CREATE_CTXT', 'description' => ''),
        1951 => array('libxml_constant' => 'XML_C14N_REQUIRES_UTF8', 'description' => ''),
        1952 => array('libxml_constant' => 'XML_C14N_CREATE_STACK', 'description' => ''),
        1953 => array('libxml_constant' => 'XML_C14N_INVALID_NODE', 'description' => ''),
        1954 => array('libxml_constant' => 'XML_C14N_UNKNOW_NODE', 'description' => ''),
        1955 => array('libxml_constant' => 'XML_C14N_RELATIVE_NAMESPACE', 'description' => ''),
        2000 => array('libxml_constant' => 'XML_FTP_PASV_ANSWER', 'description' => ''),
        2001 => array('libxml_constant' => 'XML_FTP_EPSV_ANSWER', 'description' => ''),
        2002 => array('libxml_constant' => 'XML_FTP_ACCNT', 'description' => ''),
        2003 => array('libxml_constant' => 'XML_FTP_URL_SYNTAX', 'description' => ''),
        2020 => array('libxml_constant' => 'XML_HTTP_URL_SYNTAX', 'description' => ''),
        2021 => array('libxml_constant' => 'XML_HTTP_USE_IP', 'description' => ''),
        2022 => array('libxml_constant' => 'XML_HTTP_UNKNOWN_HOST', 'description' => ''),
        3000 => array('libxml_constant' => 'XML_SCHEMAP_SRC_SIMPLE_TYPE_1', 'description' => ''),
        3001 => array('libxml_constant' => 'XML_SCHEMAP_SRC_SIMPLE_TYPE_2', 'description' => ''),
        3002 => array('libxml_constant' => 'XML_SCHEMAP_SRC_SIMPLE_TYPE_3', 'description' => ''),
        3003 => array('libxml_constant' => 'XML_SCHEMAP_SRC_SIMPLE_TYPE_4', 'description' => ''),
        3004 => array('libxml_constant' => 'XML_SCHEMAP_SRC_RESOLVE', 'description' => ''),
        3005 => array('libxml_constant' => 'XML_SCHEMAP_SRC_RESTRICTION_BASE_OR_SIMPLETYPE', 'description' => ''),
        3006 => array('libxml_constant' => 'XML_SCHEMAP_SRC_LIST_ITEMTYPE_OR_SIMPLETYPE', 'description' => ''),
        3007 => array('libxml_constant' => 'XML_SCHEMAP_SRC_UNION_MEMBERTYPES_OR_SIMPLETYPES', 'description' => ''),
        3008 => array('libxml_constant' => 'XML_SCHEMAP_ST_PROPS_CORRECT_1', 'description' => ''),
        3009 => array('libxml_constant' => 'XML_SCHEMAP_ST_PROPS_CORRECT_2', 'description' => ''),
        3010 => array('libxml_constant' => 'XML_SCHEMAP_ST_PROPS_CORRECT_3', 'description' => ''),
        3011 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_1_1', 'description' => ''),
        3012 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_1_2', 'description' => ''),
        3013 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_1_3_1', 'description' => ''),
        3014 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_1_3_2', 'description' => ''),
        3015 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_1', 'description' => ''),
        3016 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_1_1', 'description' => ''),
        3017 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_1_2', 'description' => ''),
        3018 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_1', 'description' => ''),
        3019 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_2', 'description' => ''),
        3020 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_3', 'description' => ''),
        3021 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_4', 'description' => ''),
        3022 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_5', 'description' => ''),
        3023 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_1', 'description' => ''),
        3024 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_1', 'description' => ''),
        3025 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_1_2', 'description' => ''),
        3026 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_2', 'description' => ''),
        3027 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_1', 'description' => ''),
        3028 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_3', 'description' => ''),
        3029 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_4', 'description' => ''),
        3030 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_5', 'description' => ''),
        3031 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_DERIVED_OK_2_1', 'description' => ''),
        3032 => array('libxml_constant' => 'XML_SCHEMAP_COS_ST_DERIVED_OK_2_2', 'description' => ''),
        3033 => array('libxml_constant' => 'XML_SCHEMAP_S4S_ELEM_NOT_ALLOWED', 'description' => ''),
        3034 => array('libxml_constant' => 'XML_SCHEMAP_S4S_ELEM_MISSING', 'description' => ''),
        3035 => array('libxml_constant' => 'XML_SCHEMAP_S4S_ATTR_NOT_ALLOWED', 'description' => ''),
        3036 => array('libxml_constant' => 'XML_SCHEMAP_S4S_ATTR_MISSING', 'description' => ''),
        3037 => array('libxml_constant' => 'XML_SCHEMAP_S4S_ATTR_INVALID_VALUE', 'description' => ''),
        3038 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ELEMENT_1', 'description' => ''),
        3039 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ELEMENT_2_1', 'description' => ''),
        3040 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ELEMENT_2_2', 'description' => ''),
        3041 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ELEMENT_3', 'description' => ''),
        3042 => array('libxml_constant' => 'XML_SCHEMAP_P_PROPS_CORRECT_1', 'description' => ''),
        3043 => array('libxml_constant' => 'XML_SCHEMAP_P_PROPS_CORRECT_2_1', 'description' => ''),
        3044 => array('libxml_constant' => 'XML_SCHEMAP_P_PROPS_CORRECT_2_2', 'description' => ''),
        3045 => array('libxml_constant' => 'XML_SCHEMAP_E_PROPS_CORRECT_2', 'description' => ''),
        3046 => array('libxml_constant' => 'XML_SCHEMAP_E_PROPS_CORRECT_3', 'description' => ''),
        3047 => array('libxml_constant' => 'XML_SCHEMAP_E_PROPS_CORRECT_4', 'description' => ''),
        3048 => array('libxml_constant' => 'XML_SCHEMAP_E_PROPS_CORRECT_5', 'description' => ''),
        3049 => array('libxml_constant' => 'XML_SCHEMAP_E_PROPS_CORRECT_6', 'description' => ''),
        3050 => array('libxml_constant' => 'XML_SCHEMAP_SRC_INCLUDE', 'description' => ''),
        3051 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_1', 'description' => ''),
        3052 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_2', 'description' => ''),
        3053 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_3_1', 'description' => ''),
        3054 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_3_2', 'description' => ''),
        3055 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_4', 'description' => ''),
        3056 => array('libxml_constant' => 'XML_SCHEMAP_NO_XMLNS', 'description' => ''),
        3057 => array('libxml_constant' => 'XML_SCHEMAP_NO_XSI', 'description' => ''),
        3058 => array('libxml_constant' => 'XML_SCHEMAP_COS_VALID_DEFAULT_1', 'description' => ''),
        3059 => array('libxml_constant' => 'XML_SCHEMAP_COS_VALID_DEFAULT_2_1', 'description' => ''),
        3060 => array('libxml_constant' => 'XML_SCHEMAP_COS_VALID_DEFAULT_2_2_1', 'description' => ''),
        3061 => array('libxml_constant' => 'XML_SCHEMAP_COS_VALID_DEFAULT_2_2_2', 'description' => ''),
        3062 => array('libxml_constant' => 'XML_SCHEMAP_CVC_SIMPLE_TYPE', 'description' => ''),
        3063 => array('libxml_constant' => 'XML_SCHEMAP_COS_CT_EXTENDS_1_1', 'description' => ''),
        3064 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_1_1', 'description' => ''),
        3065 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_1_2', 'description' => ''),
        3066 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_2', 'description' => ''),
        3067 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_2_1', 'description' => ''),
        3068 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT_2_2', 'description' => ''),
        3069 => array('libxml_constant' => 'XML_SCHEMAP_INTERNAL', 'description' => ''),
        3070 => array('libxml_constant' => 'XML_SCHEMAP_NOT_DETERMINISTIC', 'description' => ''),
        3071 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_1', 'description' => ''),
        3072 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_2', 'description' => ''),
        3073 => array('libxml_constant' => 'XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_3', 'description' => ''),
        3074 => array('libxml_constant' => 'XML_SCHEMAP_MG_PROPS_CORRECT_1', 'description' => ''),
        3075 => array('libxml_constant' => 'XML_SCHEMAP_MG_PROPS_CORRECT_2', 'description' => ''),
        3076 => array('libxml_constant' => 'XML_SCHEMAP_SRC_CT_1', 'description' => ''),
        3077 => array('libxml_constant' => 'XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_3', 'description' => ''),
        3078 => array('libxml_constant' => 'XML_SCHEMAP_AU_PROPS_CORRECT_2', 'description' => ''),
        3079 => array('libxml_constant' => 'XML_SCHEMAP_A_PROPS_CORRECT_2', 'description' => ''),
        3080 => array('libxml_constant' => 'XML_SCHEMAP_C_PROPS_CORRECT', 'description' => ''),
        3081 => array('libxml_constant' => 'XML_SCHEMAP_SRC_REDEFINE', 'description' => ''),
        3082 => array('libxml_constant' => 'XML_SCHEMAP_SRC_IMPORT', 'description' => ''),
        3083 => array('libxml_constant' => 'XML_SCHEMAP_WARN_SKIP_SCHEMA', 'description' => ''),
        3084 => array('libxml_constant' => 'XML_SCHEMAP_WARN_UNLOCATED_SCHEMA', 'description' => ''),
        3085 => array('libxml_constant' => 'XML_SCHEMAP_WARN_ATTR_REDECL_PROH', 'description' => ''),
        3086 => array('libxml_constant' => 'XML_SCHEMAP_WARN_ATTR_POINTLESS_PROH', 'description' => ''),
        3087 => array('libxml_constant' => 'XML_SCHEMAP_AG_PROPS_CORRECT', 'description' => ''),
        3088 => array('libxml_constant' => 'XML_SCHEMAP_COS_CT_EXTENDS_1_2', 'description' => ''),
        3089 => array('libxml_constant' => 'XML_SCHEMAP_AU_PROPS_CORRECT', 'description' => ''),
        3090 => array('libxml_constant' => 'XML_SCHEMAP_A_PROPS_CORRECT_3', 'description' => ''),
        3091 => array('libxml_constant' => 'XML_SCHEMAP_COS_ALL_LIMITED', 'description' => ''),
        4000 => array('libxml_constant' => 'XML_SCHEMATRONV_ASSERT', 'description' => ''),
        4001 => array('libxml_constant' => 'XML_SCHEMATRONV_REPORT', 'description' => ''),
        4900 => array('libxml_constant' => 'XML_MODULE_OPEN', 'description' => ''),
        4901 => array('libxml_constant' => 'XML_MODULE_CLOSE', 'description' => ''),
        5000 => array('libxml_constant' => 'XML_CHECK_FOUND_ELEMENT', 'description' => ''),
        5001 => array('libxml_constant' => 'XML_CHECK_FOUND_ATTRIBUTE', 'description' => ''),
        5002 => array('libxml_constant' => 'XML_CHECK_FOUND_TEXT', 'description' => ''),
        5003 => array('libxml_constant' => 'XML_CHECK_FOUND_CDATA', 'description' => ''),
        5004 => array('libxml_constant' => 'XML_CHECK_FOUND_ENTITYREF', 'description' => ''),
        5005 => array('libxml_constant' => 'XML_CHECK_FOUND_ENTITY', 'description' => ''),
        5006 => array('libxml_constant' => 'XML_CHECK_FOUND_PI', 'description' => ''),
        5007 => array('libxml_constant' => 'XML_CHECK_FOUND_COMMENT', 'description' => ''),
        5008 => array('libxml_constant' => 'XML_CHECK_FOUND_DOCTYPE', 'description' => ''),
        5009 => array('libxml_constant' => 'XML_CHECK_FOUND_FRAGMENT', 'description' => ''),
        5010 => array('libxml_constant' => 'XML_CHECK_FOUND_NOTATION', 'description' => ''),
        5011 => array('libxml_constant' => 'XML_CHECK_UNKNOWN_NODE', 'description' => ''),
        5012 => array('libxml_constant' => 'XML_CHECK_ENTITY_TYPE', 'description' => ''),
        5013 => array('libxml_constant' => 'XML_CHECK_NO_PARENT', 'description' => ''),
        5014 => array('libxml_constant' => 'XML_CHECK_NO_DOC', 'description' => ''),
        5015 => array('libxml_constant' => 'XML_CHECK_NO_NAME', 'description' => ''),
        5016 => array('libxml_constant' => 'XML_CHECK_NO_ELEM', 'description' => ''),
        5017 => array('libxml_constant' => 'XML_CHECK_WRONG_DOC', 'description' => ''),
        5018 => array('libxml_constant' => 'XML_CHECK_NO_PREV', 'description' => ''),
        5019 => array('libxml_constant' => 'XML_CHECK_WRONG_PREV', 'description' => ''),
        5020 => array('libxml_constant' => 'XML_CHECK_NO_NEXT', 'description' => ''),
        5021 => array('libxml_constant' => 'XML_CHECK_WRONG_NEXT', 'description' => ''),
        5022 => array('libxml_constant' => 'XML_CHECK_NOT_DTD', 'description' => ''),
        5023 => array('libxml_constant' => 'XML_CHECK_NOT_ATTR', 'description' => ''),
        5024 => array('libxml_constant' => 'XML_CHECK_NOT_ATTR_DECL', 'description' => ''),
        5025 => array('libxml_constant' => 'XML_CHECK_NOT_ELEM_DECL', 'description' => ''),
        5026 => array('libxml_constant' => 'XML_CHECK_NOT_ENTITY_DECL', 'description' => ''),
        5027 => array('libxml_constant' => 'XML_CHECK_NOT_NS_DECL', 'description' => ''),
        5028 => array('libxml_constant' => 'XML_CHECK_NO_HREF', 'description' => ''),
        5029 => array('libxml_constant' => 'XML_CHECK_WRONG_PARENT', 'description' => ''),
        5030 => array('libxml_constant' => 'XML_CHECK_NS_SCOPE', 'description' => ''),
        5031 => array('libxml_constant' => 'XML_CHECK_NS_ANCESTOR', 'description' => ''),
        5032 => array('libxml_constant' => 'XML_CHECK_NOT_UTF8', 'description' => ''),
        5033 => array('libxml_constant' => 'XML_CHECK_NO_DICT', 'description' => ''),
        5034 => array('libxml_constant' => 'XML_CHECK_NOT_NCNAME', 'description' => ''),
        5035 => array('libxml_constant' => 'XML_CHECK_OUTSIDE_DICT', 'description' => ''),
        5036 => array('libxml_constant' => 'XML_CHECK_WRONG_NAME', 'description' => ''),
        5037 => array('libxml_constant' => 'XML_CHECK_NAME_NOT_NULL', 'description' => ''),
        6000 => array('libxml_constant' => 'XML_I18N_NO_NAME', 'description' => ''),
        6001 => array('libxml_constant' => 'XML_I18N_NO_HANDLER', 'description' => ''),
        6002 => array('libxml_constant' => 'XML_I18N_EXCESS_HANDLER', 'description' => ''),
        6003 => array('libxml_constant' => 'XML_I18N_CONV_FAILED', 'description' => ''),
        6004 => array('libxml_constant' => 'XML_I18N_NO_OUTPUT', 'description' => ''),
        7000 => array('libxml_constant' => 'XML_BUF_OVERFLOW', 'description' => ''),
    );
    
    function parse($libxml_error)
    {
        $domain = null;
        
        $element = null;
        $attribute = null;
        $value = null;
        $type = null;
        $facet = null;
        $set = null;
        
        preg_match_all(
            "#\'([^\']*)\'#i", 
            $libxml_error->message, 
            $matchedArgs
        );      
        $args = $matchedArgs[1];
        
        // Remove namespace
        for($i=0; $i<count($args); $i++) {
            $args[$i] = preg_replace("#\{([^\}]*)\}#i", '', $args[$i]);
        }
        
        $domainId = (integer)substr(str_pad($libxml_error->code, 4, '0', STR_PAD_LEFT), 0, 2) - 1;
        $domainName = $this->domains[$domainId]['name'];
        $domainConst = $this->domains[$domainId]['libxml_constant'];
        
        switch($libxml_error->code) {
        case '1824':
            // Element '$1': '$2' is not a valid value of the atomic type '$3'.
            // Element '$1', attribute '$2': '$3' is not a valid value of the atomic type '$4'.
            $element = current($args);
            if(strstr($libxml_error->message, "attribute '")) $attribute = next($args);
            $value = next($args);
            $type = next($args);
            break;
            
        case '1840':
            // Element '$1': [facet '$2'] The value '$3' is not an element of the set {$4, $5, $6... $n}.
            // Element '$1', attribute '$2': [facet '$3'] The value '$4' is not an element of the set {$5, $6, $7... $n}.
            $element = current($args);
            if(strstr($libxml_error->message, "attribute '")) $attribute = next($args);
            $facet = next($args);
            $value = next($args);
            while($setItem = next($args)) $set[] = $setItem;
            break;
            
        case '1845':
            // Element 'ArchiveTransfer': No matching global declaration available for the validation root.
            $element = current($args);
            break;
            
        case '1866':
            // Element '$1', attribute '$2': The attribute '$3' is not allowed.
            $element = current($args);
            $attribute = next($args);
            break;
            
        case '1871':
            // Element '$1': This element is not expected.
            $element = current($args);
            break;
        
        case '3033':
            // Element '{http://www.w3.org/2001/XMLSchema}complexType': The content is not valid. Expected is (annotation?, (simpleContent | complexContent | ((group | all | choice | sequence)?, ((attribute | attributeGroup)*, anyAttribute?)))).
            $element = current($args);
            break;
            
        default:
            
        }
        
        $errorArgs = array(
            'level' => $libxml_error->level,
            'code' => $libxml_error->code,
            'message' => $libxml_error->message,
            'file' => $libxml_error->file,
            'line' => $libxml_error->line,
            'column' => $libxml_error->column,
            'domain' => $domainId,
            'domainConstant' => $domainConst,
            'domainName' => $domainName,
            'element' => $element,
            'attribute' => $attribute,
            'value' => $value,
            'type' => $type,
            'facet' => $facet,
            'set' => $set,
   
        );
        
        return $errorArgs;
    
    }

}
